# Generated by Django 5.2.10 on 2026-02-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='total_likes',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
